# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import qir_pb2 as qir__pb2


class EvaluatorStub(object):
  """*
  A remote QIR evaluation service.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Evaluate = channel.unary_unary(
        '/Evaluator/Evaluate',
        request_serializer=qir__pb2.Expression.SerializeToString,
        response_deserializer=qir__pb2.Expression.FromString,
        )


class EvaluatorServicer(object):
  """*
  A remote QIR evaluation service.
  """

  def Evaluate(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EvaluatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Evaluate': grpc.unary_unary_rpc_method_handler(
          servicer.Evaluate,
          request_deserializer=qir__pb2.Expression.FromString,
          response_serializer=qir__pb2.Expression.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Evaluator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
